# Generated by Django 4.2.10 on 2024-04-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_project_admin_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
