# Generated by Django 4.2.10 on 2024-05-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='geojson_file',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
