# Generated by Django 4.2.10 on 2024-05-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_geojson_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='month',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
