# Generated by Django 4.2.10 on 2024-04-16 20:26

from django.db import migrations, models
import django.db.models.deletion
import formsapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_site_status', models.BooleanField(default=0)),
                ('brigadiers', models.CharField(max_length=255)),
                ('site_name', models.CharField(max_length=100)),
                ('site_code', models.CharField(max_length=50)),
                ('latitude', formsapp.models.customFloatField()),
                ('length', formsapp.models.customFloatField()),
                ('altitude', formsapp.models.customFloatField()),
                ('type_body_water', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('season', models.CharField(max_length=50)),
                ('photo_1', models.CharField(max_length=255)),
                ('photo_2', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ph', formsapp.models.customFloatField(null=True)),
                ('amonio', formsapp.models.customFloatField(null=True)),
                ('ortofosfatos', formsapp.models.customFloatField(null=True)),
                ('water_temperature', formsapp.models.customFloatField(null=True)),
                ('environmental_temperature', formsapp.models.customFloatField(null=True)),
                ('dissolved_oxygen', formsapp.models.customFloatField(null=True)),
                ('saturation', formsapp.models.customFloatField(null=True)),
                ('turbidity', formsapp.models.customFloatField(null=True)),
                ('nitrates', formsapp.models.customFloatField(null=True)),
                ('fecal_coliforms_status', models.BooleanField(default=0)),
                ('total_coliforms', models.CharField(blank=True, max_length=50, null=True)),
                ('macroinvertebrates', models.JSONField(null=True)),
                ('macroinvertebrates_rating', formsapp.models.customFloatField(null=True)),
                ('hydromorphological_quality', formsapp.models.customFloatField(null=True)),
                ('riparian_forest_quality', formsapp.models.customFloatField(null=True)),
                ('sections', models.JSONField(null=True)),
                ('channel_width', formsapp.models.customFloatField(null=True)),
                ('object_distance_traveled', formsapp.models.customFloatField(null=True)),
                ('object_travel_time', formsapp.models.customFloatField(null=True)),
                ('shore_depth', formsapp.models.customFloatField(null=True)),
                ('volume', formsapp.models.customFloatField(null=True)),
                ('unidentified_macroinvertebrates_status', models.BooleanField(default=0)),
                ('attached_files', models.JSONField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsapp.project')),
                ('site_reference_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formsapp.site')),
            ],
            options={
                'db_table': 'sites',
            },
        ),
    ]
