# Generated by Django 4.2.10 on 2024-04-16 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='site_reference_id',
            new_name='site_reference',
        ),
    ]
