# Generated by Django 4.2.10 on 2024-04-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0003_alter_site_photo_1_alter_site_photo_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='length',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='site',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
