# Generated by Django 4.2.10 on 2024-05-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0004_rename_length_site_longitude_site_city_site_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synchronization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site_id', models.CharField(max_length=50)),
                ('scores_status', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'synchronization',
            },
        ),
    ]
