# Generated by Django 4.2.10 on 2024-05-07 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0005_synchronization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Synchronization',
        ),
    ]
