DEFAULT_PAGE_SIZE = 10
IGNORE_KEYS = [
    '_id',
    'project_id',
    'scores',
    'reference_site_scores',
    'coliformes_fecales',
    'secciones',
    'ancho_cauce',
    'distancia_recorrida_objeto',
    'tiempo_recorrido_objeto',
    'profundidad_orilla',
    'macroinvertebrados_no_identificados',
    'archivos_adjuntos',
]
EXCEL_HEADER = [
    'Cuenca',
    'Es Sitio de Referencia',
    'Sitio de Referencia Asociado',
    'Usuario',
    'Institucion',
    'Brigadistas',
    'Nomdre del Sitio',
    'Codigo del Sitio',
    'Latitud',
    'Longitud',
    'Altitud',
    'Estado',
    'Ciudad',
    'Tipo de Cuerpo de Agua',
    'Fecha',
    'Temporada',
    'Año',
    'Mes',
    'Fotografia 1',
    'Fotografia 2',
    'Notas',
    'pH',
    'Nitrógeno Amoniacal (mg/L)',
    'Ortofosfatos (mg/L)',
    'Temperatura Agua (°C)',
    'Temperatura Ambiental (°C)',
    'Oxigeno Disuelto (mg/L)',
    'Saturacion (%)',
    'Turbidez (JTU)',
    'Nitrógeno de Nitratos (mg/L)',
    'Coliformes Totales',
    'Familias de Macroinvertebrados Acuaticos',
    'Calificacion Macroinvertebrados',
    'Calidad Hidromorfologica',
    'Calidad Bosque Ribera',
    'Caudal (m³/s)',
    'Puntaje General de Calidad Ecologica',
    'Calidad General del Sitio de Monitoreo',
    'Interpretacion de la Calidad Ecologica',
]
# ARRAYS_VALUES = ['macroinvertebrados', 'secciones', 'archivos_adjuntos']
ARRAYS_VALUES = ['macroinvertebrados']
